const GET_HOTEL_DETAIL = "GET_HOTEL_DETAIL";
const GET_HOTEL_DETAIL_PENDING = "GET_HOTEL_DETAIL_PENDING";
const GET_HOTEL_DETAIL_SUCCESS = "GET_HOTEL_DETAIL_SUCCESS";
const GET_SEARCH_HOTEL = "GET_SEARCH_HOTEL";
const GET_SEARCH_HOTEL_PENDING = "GET_SEARCH_HOTEL_PENDING";
const GET_SEARCH_HOTEL_SUCCESS = "GET_SEARCH_HOTEL_SUCCESS";