export const GET_HOTEL_DETAIL = "GET_HOTEL_DETAIL";
export const GET_HOTEL_DETAIL_PENDING = "GET_HOTEL_DETAIL_PENDING";
export const GET_HOTEL_DETAIL_SUCCESS = "GET_HOTEL_DETAIL_SUCCESS";
export const GET_HOTEL_DETAIL_FAILED = "GET_HOTEL_DETAIL_FAILED";
export const GET_SEARCH_HOTEL = "GET_SEARCH_HOTEL";
export const GET_SEARCH_HOTEL_PENDING = "GET_SEARCH_HOTEL_PENDING";
export const GET_SEARCH_HOTEL_SUCCESS = "GET_SEARCH_HOTEL_SUCCESS";
export const GET_SEARCH_HOTEL_FAILED = "GET_SEARCH_HOTEL_FAILED";
//SEARCH BY FILTER
export const GET_SEARCH_HOTEL_BY_FILTER = "GET_SEARCH_HOTEL_BY_FILTER";
export const GET_SEARCH_HOTEL_BY_FILTER_PENDING = "GET_SEARCH_HOTEL_BY_FILTER_PENDING";
export const GET_SEARCH_HOTEL_BY_FILTER_SUCCESS = "GET_SEARCH_HOTEL_BY_FILTER_SUCCESS";
export const GET_SEARCH_HOTEL_BY_FILTER_FAILED = "GET_SEARCH_HOTEL_BY_FILTER_FAILED";
//SEARCH SUGGESTION
export const GET_SEARCH_SUGGESTION = "GET_SEARCH_SUGGESTION";
export const GET_SEARCH_SUGGESTION_PENDING = "GET_SEARCH_SUGGESTION_PENDING";
export const GET_SEARCH_SUGGESTION_SUCCESS = "GET_SEARCH_SUGGESTION_SUCCESS";
export const GET_SEARCH_SUGGESTION_FAILED = "GET_SEARCH_SUGGESTION_FAILED";