export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REQUEST_LOGGING = "REQUEST_LOGGING";
export const LOGGING_FAILED = "LOGGING_FAILED";
export const LOGGING_SUCCESS = "LOGGING_SUCCESS";
export const LOGIN_SCREEN = "LOGIN_SCREEN";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
